### PR TITLE
Improve fiber plotting speed by factor 176 ;-)

### PR DESCRIPTION
**Pull request by adhusch**
Please test and check for regressions.

Before (880s):
screenshot 2019-03-07 at 09 23 20

After (6s):
screenshot 2019-03-07 at 10 44 38

### CODE REVIEW

**Comment by andreashorn** [comment]
Hi @adhusch am travelling and currently no time to check. What exactly should I test and could you potentially test on your side?
Thanks!

**Comment by adhusch** [comment]
Currently it doesnt support the "show==false" parameter returning only an FV but not plotting it (like it is/was for lines). I am not clear about that. When its really only about not showing i could solve it otherwise, when its about really needing an FV its more complicated. I dont know about potential sideeffects of this. Only for plotting it should look identical now.

**Comment by adhusch** [comment]
Further update:

Before:
screenshot 2019-03-07 at 13 54 07

After:
screenshot 2019-03-07 at 13 48 45

**Comment by andreashorn** [comment]
Hi @adhusch, it should indeed support the show==false option because sometimes we want to get the fv and then reduce it first before showing it (or save it). One could also have a subfunction that builds the tract and then one that plots it, which would probably be cleaner. But as it is, it would break things somewhere.

**Comment by adhusch** [comment]
I will try to see if I can make the show=false work, should be possible... 

o = streamtube(..);
surf2patch(o(1..N)); 

sort of

**Comment by adhusch** [comment]
If this doesn't work with out a lot of work: what about a third plot option: 'tube', 'line' and 'stream tube'?

**Comment by adhusch** [comment]
Should work now with the FV. But actually I find the fibers look somehow nicer as surfaces (stream tubes)

**Pull request merged**
