### PR TITLE
Fix FSL binaries on Windows.

### PR DESCRIPTION
**Pull request by ningfei**

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@ningfei, may you wait at least for ARTENOLIS to finish before merging? 👍 

@loicmarx, maybe it has to do with this PR that #210 is failing. May you rebase one more time?

**Comment by ningfei** [comment]
@laurentheirendt sorry, was on the run. and wanted to update it quickly. Some user reported me they encountered problem on windows. Will wait for ARTENOLIS next time. :+1: 

Checked the error log of #210, seems not related to this PR. On Windows and Mac, it's still SPM problem. On Linux, seems an java exception related to opengl.

**Comment by laurentheirendt** [comment]
No worries ;) Sometimes when the PR is closed, the build status is not reported properly and the commit status stays as `pending`.

The SPM problem shall be solved, at least on Linux. Investigating ...

**Comment by ningfei** [comment]
Okay, good to know :)

**Pull request merged**
