### PR TITLE
Fiber filtering save and load functionality

### PR DESCRIPTION
**Pull request by GaranceMeyer**
Written by Michael Loftus
Save and load buttons added to Tools dropdown menu on the fiber filtering GUI so that the user can save and load fiber filtering settings
Irrelevant modification to ea_discfibers/ea_discfibers_calcstats.m

### CODE REVIEW

**Comment by ningfei** [comment]
Cool, thanks! So modifications to ea_discfibers/ea_discfibers_calcstats.m are irrelevant but necessary? Especially for `ea_disctract.m`, I see almost everything changed. What's in that?

**Comment by GaranceMeyer** [comment]
Hi Ningfei,

The changes made to ea_discfibers_calcstats.m don't have anything to do with the code's functionality.  It can be disregarded for the save/load settings buttons I wrote, I should've removed it from the commit.  Since I pushed from Garance's computer, I would guess that it's a code block that she uncommented for her own use.

For ea_disctract, the code should be functionally identical to the way it was before.  I wrote some changes that I later transferred into ea_save_settings and ea_load_settings, so the only thing that I would expect to change in ea_disctract is the whitespace.  I see that for some reason, git is picking up on changes where the code appears to be identical.
________________________________
Von: Meyer, Garance ***@***.***>
Gesendet: Freitag, 4. August 2023 16:59
An: Loftus Iii, Michael Edward ***@***.***>
Betreff: Fwd: [netstim/leaddbs] Fiber filtering save and load functionality (PR #1066)



Begin forwarded message:

**Comment by ningfei** [comment]
Okay. Good to know. I just checked, it's only line ending. We use Unix line ending by default ('\n'). In the ea_disctract.m, you changed it to Windows line ending. That's why it seems everything was modified. I will take care of it locally and then merge it.

**Comment by loftusmi3** [comment]
Got it, thank you. Sorry about that!

**Comment by ningfei** [comment]
Merged in 53efde74

**Pull request closed without merging**
