### PR TITLE
BUG: fix for lead_import, clean up code and deprecated/unused variables that caused the importer to fail

### PR DESCRIPTION
**Pull request by oprienrico**
Many import scenario seem to now fail (tested on windows and ubuntu).
It is due to a deprecated "results" variable, which was used as output of methods in a previous version of the code. However, now many methods have already been rewritten to not use that variable (using/setting properties in app variable), and do not set it at their output.
Some methods still call the methods with results, which then causes a failure in a variety of scenarios (including loading when converting from non BIDS folders)
within: function startupFcn(app, source_folder, options, handles, dest_folder)
with error: Unrecognized function or variable 'results'.
Error in lead_import/startupFcn (line 457)
                if strcmp(results,'fail')
or within: function results = reset_rules(app) (which did not return or set results)
Now refactored and checked

Other fixes:
1) enablerules(app,selection) is called with different argument numbers (which is not handled by the function itself). Refactor for consistency.

2) some other old leftover code (for example)
               from: setappdata(app.handles.leadfigure, 'BIDSRoot', dest{1});
               to : setappdata(app.handles.leadfigure, 'BIDSRoot', app.output_folder{1});

3) handling/avoiding triggering warnings
check if folder exist, and trigger creation only if necessary (to avoid warnings)
as for example: mkdir(fullfile(selection,'DICOM'))

### CODE REVIEW

**Comment by ningfei** [comment]
Thanks! @nrajamani3 could you please check and follow up on this one?

**Comment by oprienrico** [comment]
Hi @nrajamani3 , also on another note, to keep track of code changes, we may want to include also the "generated" .m code.
This is also what is suggested by MATLAB Team:
"The current recommended workflow for version controlling MLAPP files with Git is to export the MLAPP file to a MATLAB code file (.m) and check-in this exported MATLAB code file with the MLAPP file."

Source: https://www.mathworks.com/matlabcentral/answers/524615-can-i-integrate-mlapp-files-from-app-designer-with-git-source-control

otherwise, there is still the convoluted diff-checker integrated in app designer:
https://www.youtube.com/watch?v=v-dBlyTSXRU

**Comment by nrajamani3** [comment]
@oprienrico thank you so much for the PR and possible changes! I'm able to review them now and will get back to you soon!!

**Comment by nrajamani3** [comment]
ok, checked, can be merged and closed now.

**Comment by oprienrico** [comment]
@nrajamani3 thank you for checking and reviewing it!

**Pull request merged**
