### PR TITLE
Add coverage for leaddbs

### PR DESCRIPTION
**Pull request by loicmarx**
This PR include the add and modification of the following files:  
	test/base/clearGlobal.m
	test/base/getEnvironment.m
	test/base/getFilesInDir.m
	test/base/getGlobalValue.m
	test/base/getIgnoredFiles.m
	test/base/restoreEnvironment.m
	test/base/runScriptFile.m
	test/base/runTestSuite.m
	test/base/setGlobal.m

### CODE REVIEW

**Comment by ningfei** [comment]
Great! Thank you @laurentheirendt @loicmarx  so much for the work! We are really having testings now.
Regarding the errors here, seems still the SPM not installed issue?

**Comment by laurentheirendt** [comment]
Yes, that is the issue. I am looking into it. 👍 

This is primarily the testing framework properly speaking - tests will follow over the summer.

**Comment by laurentheirendt** [comment]
@ningfei, there was no need to merge the `develop` onto this PR - ARTENOLIS runs a merged version of the code. 

@loicmarx, may you remove this merge? Thanks 👍

**Comment by ningfei** [comment]
I see! I merged it since I saw conflict. So @loicmarx will make a new PR?

**Comment by laurentheirendt** [comment]
no, @loicmarx will just reset it.

**Comment by ningfei** [comment]
okay :)

**Comment by ningfei** [comment]
you can merge this whenever you think it's ready @loicmarx :)

**Comment by laurentheirendt** [comment]
I will merge 😄

**Comment by laurentheirendt** [comment]
Re-trigger build

**Comment by laurentheirendt** [comment]
Thanks @loicmarx 👍 

The test is only there for triggering the test suite properly. Codecov did not reply, as there is no base coverage report. This will (hopefully) happen in the next PR.

**Pull request merged**
