### PR TITLE
Di o de sensight and manual

### PR DESCRIPTION
**Pull request by Till-Dembek**
Hey Ningfei!

I added some stuff for Sensight lead suppor as well as a new manual workflow for orientation detection!

Best ~Till

### CODE REVIEW

**Comment by ningfei** [comment]
Thanks @Till-Dembek, that's great! Do you still want to do more tests @oprienrico ?

**Comment by oprienrico** [comment]
Sorry did not reply here as well due to the Slack.
I will do some tests on the side, as mentioned in the Slack. Looks running now!

**Comment by ningfei** [comment]
great, thanks! I'm also testing it on the develop (bids) branch. If everything works fine, will make a patch release for the current stable version.

**Comment by ningfei** [comment]
@oprienrico results seems correct from my side, GUI sometimes hung on or didn't pop up. Will look into it.

**Comment by oprienrico** [comment]
i saw your push. i will discard my temporary branch and work from the develop. Will let you know as well. Results looked fine as well, but will check with few patients

**Pull request merged**
