### PR TITLE
Fix screenshot export

### PR DESCRIPTION
**Pull request by jAchtzehn**
This PR fixes issues where a wrong figure is selected during the exporting of a patient, resulting in incorrect views for the .png files.

Adds the possibility to parse a figure handle to ea_screenshot in order to avoid scenarios where a wrong figure is selected by the default behavior of export_fig.m (gcf). If no figure handle is parsed, gcf will be called to the the current figure (just as before).

Fixes issue #486

### CODE REVIEW

**Comment by ningfei** [comment]
HI Johannes, thanks for PR! Seems there're 3 additional files from MNI_PD space folder pushed here?

**Comment by jAchtzehn** [comment]
Thanks for pointing that out @ningfei, they accidentally got commited... I reverted that commit and now only 2 files are changed. Should be good to go.

**Comment by ningfei** [comment]
Thanks! Merged now :) Btw, I would suggest to reset local repository to the head of the upstream develop branch or rebase before committing fixes, instead of merging back from upstream develop branch (especially when your local repo is in line with and doesn't diverge from upstream). Thus we have a more linear commit history and don't have too much mergings between branches.

**Comment by jAchtzehn** [comment]
Thanks for the good suggestion, will do so in the future.

**Pull request merged**
