### PR TITLE
UPD works on matrices not only column vectors

### PR DESCRIPTION
**Pull request by GaranceMeyer**
This function is used on a matrix of clinical scores rather than vectors for the PCA option of the fiberfiltering tool, such as the z-score computation was wrong. Made the function work for both column vectors and matrices with one score per column.

### CODE REVIEW

**Comment by ningfei** [comment]
the old version works for both row and column vector. Now it seems only working for column vector (and matrix)?

**Comment by ningfei** [comment]
Closed by 1eee831. Refactored in 829ef13. Please double check if everything is working as expected @GaranceMeyer @nrajamani3 Thanks!

**Comment by GaranceMeyer** [comment]
Hi Ningfei,
Indeed I was talking about that with Nanditha, I was not sure if it should work on row vectors and she was not sure either.
So, if it has to work on row vectors, then it is not fine this way. I can correct it if needed.

Garance Meyer
Postdoctoral Research Fellow
Netstim lab (PI: Andreas Horn)
Center for Brain Circuit Therapeutics, Department of Neurology
Brigham and Women’s Hospital - Harvard Medical School

***@***.******@***.***>
75 Francis St, Boston, MA 02115



On Sep 5, 2022, at 3:25 PM, Ningfei Li ***@***.******@***.***>> wrote:


        External Email - Use Caution



the old version works for both row and column vector. Now it seems only working for column vector (and matrix)?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1TO_4lMF8gnRJ8iVvfUOwi0pUbc8HwK6qctJONMC8YhIcxyl0b8X9SuNrkxvIl76SJXYwuaEMzN66dAunLeosiA3AcpJiSSQzMpBwCHav9rdnLmE5tD4c0BdTPEFLVOhVLDmri6QkN-iYAWs-bhTiHh1B27Ubguv9KjIO27r27weiS1_fw47g4ugfKnqUK0AzryXz5BOCGtAgcPq_N6SeSfLNVf4w34i9nYz0ylzXN3eT7bsqOE70RQLHQi57epJ-oO0g1kP2ZcMCawLcebdyDRzdx4UM1iZBQUu-4dyBUR1M9t0NP4kka-We94MqYFB_ZbyeOgbTrZ6IlWt3DLShFg/https%3A%2F%2Fgithub.com%2Fnetstim%2Fleaddbs%2Fpull%2F812%23issuecomment-1237407639>, or unsubscribe<https://secure-web.cisco.com/1CHrXln7SSLW-vX-0PFT7wX-ikkE3YJyLjvsb9BBX12I68bMveyBAZg0KBD6ztyjrj_0SDSGU9GsK2nTjLS4tsDQ8bDDAXYo-WYWg6_6NUaFDH2vBH4Eimff55jlq_13Y_oe6hy2hbQtnNMFjpisfjzmVIjwIidrHJU6lds8d1xhE1m2RlneSRsH-eftkBdrHKZpIIPMqT7scRvLBA-Cv3glWJmwKgnVExo6ipIDjipUDwKAtAxgC_PVlMludYtHXlCgQzPxZGfdXNnh6ENgVaP-dOlrHTl0s9BC-0HBwd8NvRpY-qcvRb5scr3w6r7xEZ-gQigokeLeGIUK-9d6VhQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ3FHV237TNFNHXPIER7MFLV4ZCJVANCNFSM6AAAAAAQDLDFVU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by ningfei** [comment]
@GaranceMeyer  Nanditha already resolved here #838. We support both column and row vector for compatibility consideration. The code is now already pretty much simplified: https://github.com/netstim/leaddbs/blob/develop/ext_libs/nan/ea_nanzscore.m

**Pull request closed without merging**
