### PR TITLE
Massive speed improvement

### PR DESCRIPTION
**Pull request by adhusch**
Massive speed improvement replacing ea_intriangulation by inpolydedron. In my test case from > 30 min to < 5 min but should be confirmed on other data and i didnt do extensive check for potential other causes why it was so slow in my original test.

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Wouldn't this PR need to be merged now against `develop`?

**Comment by andreashorn** [comment]
Yes, should be merged against develop, true. Can we change this or do we need a new PR?

**Comment by laurentheirendt** [comment]
You may change the target branch (usually by clicking on `master` on top of this page, a dropdown menu appears).

**Comment by ningfei** [comment]
The new function `inpolyhedron` seems an external function which also needs to be included here?

**Comment by andreashorn** [comment]
It's in the PaCER code on my side.

**Comment by andreashorn** [comment]
I'd recommend to change such functions to e.g. ea_inpolyhedron.m to make them specific – since some people have a lot of crap on their paths and by changing their name it's possible to be certain the right function is being used. Just for future reference.

**Comment by ningfei** [comment]
then maybe a copy in leaddbs `ext_libs` folder with the name `ea_inpolyhedron.m`? this might also be used elsewhere in the future I think.

**Comment by andreashorn** [comment]
Hi @adhusch, on my side this seems to select fibers that are outside the VTA, as well. Could you maybe confirm?
Thanks!

bildschirmfoto 2019-03-06 um 11 21 10

**Comment by adhusch** [comment]
Will check. Maybe the surface normals point in the wrong direction..

**Comment by adhusch** [comment]
@andreashorn could you plot again please?

**Comment by andreashorn** [comment]
bildschirmfoto 2019-03-06 um 17 42 14
Now it seems to work!

**Comment by adhusch** [comment]
Cool. I think that was a nice example how the workflow could look like in the future :)

**Comment by andreashorn** [comment]
Yes! Just need other people to test :) too busy myself (at least these days).

**Comment by laurentheirendt** [comment]
**ARTENOLIS** will help soon to automate the tests! 👍 😄

**Comment by andreashorn** [comment]
Yup yup!

**Pull request merged**
